### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by UrfinJuice11** [jarnoaxel/python-wireguard#26]
On the PyPi page ([https://pypi.org/project/python-wireguard/](https://pypi.org/project/python-wireguard/)) the server creating string is:

server = Server("wg-srv", private, 12345, "10.0.0.1/24")

But the Server class is awaiting for another order:

server = Server("wg-srv", private, "10.0.0.1/24", 12345)

**Comment by jarnoaxel** [comment]
Thanks for noticing the mistake! I had already updated it on Github but forgot to deploy a new release to PyPI as there were no code changes (only the documentation). I have made a new release including the correct README.md file from Github and it's now correct on PyPI.
